import json
import logging
from typing import Dict, Any, Tuple, Optional
from llm_service import invoke_with_fallback

logger = logging.getLogger(__name__)

class ContentEngineer:
    """
    Autonomous Content Engineer.
    Executes a three-stage pipeline to generate, format, and prepare a blog for DB insertion.
    """
    
    SYSTEM_PROMPT = """You are an Autonomous Content Engineer. Your goal is to take a single [TOPIC] and execute a three-stage pipeline to generate, format, and prepare a blog for database insertion.

Stage 1: Knowledge Generation
Generate a deep-dive, technical explanation of the [TOPIC].
Ensure the content covers "What is it", "Why is it needed", "Core Components", and a "Conclusion".
Tone: Professional, educational, and developer-focused.

Stage 2: Structural Formatting (The HTML Rulebook)
Transform the text from Stage 1 into raw HTML using these strict rules:
Tags: Use <h2> for main sections, <h3> for subsections, <p> for body text, and <ul>/<li> for lists.
Code: Wrap any code in <pre><code class="language-java"> (or the relevant language).
Spacing: Maximum ONE blank line between sections. No blank lines inside paragraphs.
Cleaning: Remove all Markdown backticks (```). Return ONLY the HTML string.

Stage 3: Payload Construction (DB Insertion)
Construct a final JSON object for the POST request to https://techxbytes.com/api/blogs.
Required JSON Structure:
{
  "title": "[Generated Title]",
  "content": "[The HTML from Stage 2]",
  "author": {
    "userId": "d2b8dc2b-c9fa-4f70-9484-597c0097bff4",
    "name": "kabir-b013b4"
  },
  "category": "java",
  "isPremium": false,
  "isPublished": true,
  "tags": ["[topic-related-tag]"]
}

Instruction: When I provide a topic, output the final JSON payload only. Do not wrap the output in markdown code blocks like ```json.
"""

    @staticmethod
    def generate_blog_payload(
        topic: str, 
        provider: str = "google", 
        model_name: Optional[str] = None,
        prefer_model: Optional[str] = None
    ) -> Tuple[str, str, str, Dict[str, Any]]:
        """
        Executes the pipeline.
        Returns:
            Tuple containing:
            - Content (str): The raw JSON payload generated by the LLM
            - Provider Used (str)
            - Model Used (str)
            - Metadata (Dict)
        """
        prompt = f"{ContentEngineer.SYSTEM_PROMPT}\n\nTopic: [{topic}]"

        ai_message, provider_used, model_used = invoke_with_fallback(
            prompt, provider, model_name, prefer_model
        )

        response_text = ai_message.content
        if isinstance(response_text, list):
            response_text = "".join(
                block.get("text", "") if isinstance(block, dict) else str(block) 
                for block in response_text
            )
            
        # Clean up in case the LLM wrapped it in markdown quotes
        cleaned_text = response_text.strip()
        if cleaned_text.startswith("```json"):
            cleaned_text = cleaned_text[7:]
        elif cleaned_text.startswith("```"):
            cleaned_text = cleaned_text[3:]
        if cleaned_text.endswith("```"):
            cleaned_text = cleaned_text[:-3]
            
        return cleaned_text.strip(), provider_used, model_used, getattr(ai_message, 'response_metadata', {})

if __name__ == "__main__":
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(description="Autonomous Content Engineer Pipeline")
    parser.add_argument("topic", type=str, help="Topic to generate the blog for")
    parser.add_argument("--provider", type=str, default="google", help="LLM Provider")
    parser.add_argument("--model", type=str, default=None, help="LLM Model Name")
    args = parser.parse_args()
    
    payload, p, m, _ = ContentEngineer.generate_blog_payload(args.topic, args.provider, args.model)
    print(f"--- Generated using {p} ({m}) ---")
    print(payload)
