apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
  namespace: judge0
data:
  judge0.conf: |
    [server]
    host = "0.0.0.0"
    port = 2358

    [database]
    hostname = "postgres"
    port = 5432
    username = "judge0"
    database = "judge0_db"

    [redis]
    hostname = "redis"
    port = 6379
